### PR TITLE
Readd Windows Python 3.8

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #39.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes https://github.com/conda-forge/llvmlite-feedstock/issues/35
Closes https://github.com/conda-forge/llvmlite-feedstock/issues/39

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@anaconda-pkg-build, how do you handle this problem? Basically `llvmlite` seems to not be able to load the `dll` here any more on Windows Python 3.8. This caused us issues last release, `0.33.0`, and now this one,  `0.34.0`.

**Comment by mbargull** [comment]
Didn't notice the `autobump` label and didn't cancel drone/travis builds in time...

**Comment by mbargull** [comment]
Also didn't notice the build number hasn't been bumped. Which is actually a good thing because it means the Drone/Travis jobs didn't matter since no new builds have been created.
For whatever reason Azure builds also didn't trigger on `master` -- which is also good because of the unintentional merge. But it's odd that those weren't triggered at all, nonetheless...

**Comment by mbargull** [comment]
> @anaconda-pkg-build, how do you handle this problem?

Looks like they worked around that by static linking:
https://github.com/AnacondaRecipes/llvmlite-feedstock/commit/b4338dc785c7b8aba3aa0efdb60d6011ef1a9ee2

**Comment by jakirkham** [comment]
No worries 😉 We built all the other packages before. So it was just a matter of building the Windows Python 3.8 packages.

**Pull request merged**
