### PR TITLE
0.42.0rc1 release

### PR DESCRIPTION
**Pull request by gmarkall**
Testing 0.42 on conda-forge before we tag the release, to avoid issues seen previously where we only discovered problems once the conda-forge package started building (see e.g. #74, #76).

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
Have pushed a few changes here:

* Required Python 3.9 as a minimum (was erroring about this with Python 3.8)
* Merged in the Python 3.12 migrator from PR ( https://github.com/conda-forge/llvmlite-feedstock/pull/75 )
* Readded templating in URL
* Re-rendered to pick up latest changes (and apply skips, migrators, etc.)

Think that should cut out some false positives and address some false negatives. Hope that is ok

**Comment by jakirkham** [comment]
Looks like there is an issue with Windows Python 3.12 [on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=863655&view=logs&jobId=e5cdccbf-4751-5a24-7406-185c9d30d021&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=0c979b57-e97b-5e0a-363d-f964823a2ab0 ):

```python
(%BUILD_PREFIX%) %SRC_DIR%>%PREFIX%\python.exe -S setup.py install 
Traceback (most recent call last):
  File "D:\bld\llvmlite_1706051857045\work\setup.py", line 2, in <module>
    from setuptools import setup, Extension
ModuleNotFoundError: No module named 'setuptools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bld\llvmlite_1706051857045\work\setup.py", line 6, in <module>
    from distutils.core import setup, Extension
ModuleNotFoundError: No module named 'distutils'
```

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by gmarkall** [comment]
@jakirkham Many thanks for the fixes - the retargeting to `rc` and the change back to PyPI + templating look good!

**Comment by jakirkham** [comment]
Glad to hear it. Thanks for all the work here Graham! 🙏

Let's merge and see how these packages perform

**Pull request merged**
