### PR TITLE
v0.43.0rc1

### PR DESCRIPTION
**Pull request by gmarkall**
This also includes a merge of `main` into the `rc` branch. The only substantial change is https://github.com/conda-forge/llvmlite-feedstock/pull/86/commits/1cd97d6917e3e09e54ec656b2adb51e7c0965015, which just changes the version number, tarball location, sha256sum, and build number.

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gmarkall** [comment]
Adding `stdlib("c")` did not seem to work, so although I tried it, I've reverted it for now - I'd prefer to handle it separately from building the RC version.

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
> Adding `stdlib("c")` did not seem to work, so although I tried it, I've reverted it for now - I'd prefer to handle it separately from building the RC version.

Ah ok. This is mostly cosmetic. It pulls in these dependencies already. We are just trying to be explicit, which will help when we change the GLIBC version conda-forge builds with

As to why it failed, think all we were missing was a re-render, which I've just now tried and expect to work

That said, if we run into other issues, happy to punt on this

**Comment by jakirkham** [comment]
Do we want to try LLVM 15 given this release has support for it? Or do you want to wait on that?

**Comment by gmarkall** [comment]
Thanks for the review!

> Do we want to try LLVM 15 given this release has support for it? Or do you want to wait on that?

I don't want to try it because it's only experimental. It'd be better just just get the RC out.

**Comment by jakirkham** [comment]
Sounds good. Merged

Thanks Graham! 🙏

**Pull request merged**
