### PR TITLE
MNT: rerender

### LINKED ISSUE #45: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #45.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #45

Rebuild with packages from PR ( https://github.com/conda-forge/llvmdev-feedstock/pull/98 ).

### CODE REVIEW

**Comment by jakirkham** [comment]
Looks like the Drone CI builds are [failing with a segfault]( https://cloud.drone.io/conda-forge/llvmlite-feedstock/36 ).

```python
===== testing package: llvmlite-0.34.0-py38h4f45e52_1 =====
672	running run_test.py
673	..s...........Fatal Python error: Illegal instruction
674	
675	Current thread 0x0000ffffbc0ad000 (most recent call first):
676	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/binding/ffi.py", line 113 in __call__
677	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/binding/executionengine.py", line 98 in run_static_constructors
678	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/test_binding.py", line 1344 in test_global_ctors_dtors
679	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/case.py", line 633 in _callTestMethod
680	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/case.py", line 676 in run
681	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/case.py", line 736 in __call__
682	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 122 in run
683	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 84 in __call__
684	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 122 in run
685	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 84 in __call__
686	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 122 in run
687	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 84 in __call__
688	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/runner.py", line 176 in run
689	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/main.py", line 271 in runTests
690	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/customize.py", line 97 in run_tests_real
691	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/customize.py", line 112 in runTests
692	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/main.py", line 101 in __init__
693	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/customize.py", line 38 in __init__
694	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/__init__.py", line 50 in run_tests
695	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/__init__.py", line 56 in main
696	  File "/drone/src/build_artifacts/llvmlite_1598560627310/test_tmp/run_test.py", line 11 in <module>
697	/drone/src/build_artifacts/llvmlite_1598560627310/test_tmp/conda_test_runner.sh: line 2:  1444 Illegal instruction     (core dumped) "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python" -s "/drone/src/build_artifacts/llvmlite_1598560627310/test_tmp/run_test.py"
```

**Comment by stuartarchibald** [comment]
> Looks like the Drone CI builds are [failing with a segfault](https://cloud.drone.io/conda-forge/llvmlite-feedstock/36).
> 
> ```python
> ===== testing package: llvmlite-0.34.0-py38h4f45e52_1 =====
> 672	running run_test.py
> 673	..s...........Fatal Python error: Illegal instruction
> 674	
> 675	Current thread 0x0000ffffbc0ad000 (most recent call first):
> 676	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/binding/ffi.py", line 113 in __call__
> 677	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/binding/executionengine.py", line 98 in run_static_constructors
> 678	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/test_binding.py", line 1344 in test_global_ctors_dtors
> 679	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/case.py", line 633 in _callTestMethod
> 680	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/case.py", line 676 in run
> 681	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/case.py", line 736 in __call__
> 682	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 122 in run
> 683	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 84 in __call__
> 684	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 122 in run
> 685	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 84 in __call__
> 686	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 122 in run
> 687	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/suite.py", line 84 in __call__
> 688	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/runner.py", line 176 in run
> 689	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/main.py", line 271 in runTests
> 690	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/customize.py", line 97 in run_tests_real
> 691	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/customize.py", line 112 in runTests
> 692	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/unittest/main.py", line 101 in __init__
> 693	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/customize.py", line 38 in __init__
> 694	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/__init__.py", line 50 in run_tests
> 695	  File "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.8/site-packages/llvmlite/tests/__init__.py", line 56 in main
> 696	  File "/drone/src/build_artifacts/llvmlite_1598560627310/test_tmp/run_test.py", line 11 in <module>
> 697	/drone/src/build_artifacts/llvmlite_1598560627310/test_tmp/conda_test_runner.sh: line 2:  1444 Illegal instruction     (core dumped) "/drone/src/build_artifacts/llvmlite_1598560627310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python" -s "/drone/src/build_artifacts/llvmlite_1598560627310/test_tmp/run_test.py"
> ```

hmmm, SIGILL. The last LLVM build worked ok didn't it?

**Comment by jakirkham** [comment]
That's right.

cc @conda-forge/llvmdev (in case others have insights here)

**Comment by jakirkham** [comment]
FWIW here's [the last `aarch64` build logs]( https://cloud.drone.io/conda-forge/llvmlite-feedstock/33 ).

**Comment by stuartarchibald** [comment]
Don't suppose you can run the tests under `catchsegv`? It might give a better backtrace. Thanks.

**Comment by isuruf** [comment]
https://github.com/conda-forge/llvmdev-feedstock/pull/99

**Comment by jakirkham** [comment]
@conda-forge-admin, please restart CI.

**Comment by jakirkham** [comment]
Looks like that fixed the `aarch64` builds. Thanks @isuruf! 😄 🎉

**Comment by stuartarchibald** [comment]
Thanks @isuruf

**Pull request merged**
